import { useState, useRef } from 'react';
import { Sparkles, Loader2, Download } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { useAuth } from '@/contexts/AuthContext';
import { useToast } from '@/hooks/use-toast';
import type { Gem } from '@/data/gems';
import { categoryInfo } from '@/data/gems';
import { Link } from 'react-router-dom';
import DOMPurify from 'dompurify';
import { supabase } from '@/integrations/supabase/client';
import jsPDF from 'jspdf';

const simpleMarkdown = (text: string) =>
  text
    .replace(/### \*\*(.*?)\*\*/g, '<h3 class="font-display font-semibold text-base mt-4 mb-2 text-foreground">$1</h3>')
    .replace(/### (.*)/g, '<h3 class="font-display font-semibold text-base mt-4 mb-2 text-foreground">$1</h3>')
    .replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>')
    .replace(/\*(.*?)\*/g, '<em>$1</em>')
    .replace(/^---$/gm, '<hr class="my-3 border-border"/>')
    .replace(/^\* {2}/gm, '• ')
    .replace(/\n/g, '<br/>');

const downloadPdf = (itinerary: string, gemName: string) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  const maxWidth = pageWidth - margin * 2;
  let y = 20;

  // Title
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text(`Travel Itinerary: ${gemName}`, margin, y);
  y += 12;

  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(120);
  doc.text(`Generated by Hidden Gems of India • ${new Date().toLocaleDateString()}`, margin, y);
  y += 10;
  doc.setTextColor(0);

  // Line separator
  doc.setDrawColor(200);
  doc.line(margin, y, pageWidth - margin, y);
  y += 8;

  // Process content line by line
  const cleanText = itinerary
    .replace(/### \*\*(.*?)\*\*/g, '### $1')
    .replace(/\*\*(.*?)\*\*/g, '$1')
    .replace(/\*(.*?)\*/g, '$1');

  const lines = cleanText.split('\n');

  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed) {
      y += 4;
      continue;
    }

    const isHeading = trimmed.startsWith('### ') || trimmed.startsWith('## ') || trimmed.startsWith('# ');
    const isSeparator = trimmed === '---';

    if (isSeparator) {
      doc.setDrawColor(220);
      doc.line(margin, y, pageWidth - margin, y);
      y += 6;
      continue;
    }

    if (isHeading) {
      y += 4;
      doc.setFontSize(12);
      doc.setFont('helvetica', 'bold');
      const headingText = trimmed.replace(/^#{1,3}\s*/, '');
      const wrapped = doc.splitTextToSize(headingText, maxWidth);
      for (const wl of wrapped) {
        if (y > doc.internal.pageSize.getHeight() - 20) { doc.addPage(); y = 20; }
        doc.text(wl, margin, y);
        y += 6;
      }
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(10);
    } else {
      doc.setFontSize(10);
      doc.setFont('helvetica', 'normal');
      const wrapped = doc.splitTextToSize(trimmed, maxWidth);
      for (const wl of wrapped) {
        if (y > doc.internal.pageSize.getHeight() - 20) { doc.addPage(); y = 20; }
        doc.text(wl, margin, y);
        y += 5;
      }
    }
  }

  doc.save(`${gemName.replace(/\s+/g, '-').toLowerCase()}-itinerary.pdf`);
};

const ItineraryGenerator = ({ gem }: { gem: Gem }) => {
  const [itinerary, setItinerary] = useState('');
  const [loading, setLoading] = useState(false);
  const { user } = useAuth();
  const { toast } = useToast();
  const abortRef = useRef<AbortController | null>(null);

  const generate = async () => {
    if (!user) return;
    setLoading(true);
    setItinerary('');

    try {
      abortRef.current = new AbortController();
      const info = categoryInfo[gem.category];

      const { data: { session } } = await supabase.auth.getSession();
      const resp = await fetch(`${import.meta.env.VITE_SUPABASE_URL}/functions/v1/generate-itinerary`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          Authorization: `Bearer ${session?.access_token}`,
        },
        body: JSON.stringify({
          gemName: gem.name,
          gemState: gem.state,
          gemDescription: gem.description,
          gemCategory: info.label,
          gemHighlight: gem.highlight,
        }),
        signal: abortRef.current.signal,
      });

      if (!resp.ok) {
        const data = await resp.json();
        if (resp.status === 429) {
          toast({ title: 'Rate Limited', description: 'Too many requests. Please try again later.', variant: 'destructive' });
        } else if (resp.status === 402) {
          toast({ title: 'Credits Required', description: 'AI credits need to be topped up.', variant: 'destructive' });
        } else {
          toast({ title: 'Error', description: data.error || 'Failed to generate itinerary', variant: 'destructive' });
        }
        setLoading(false);
        return;
      }

      const reader = resp.body?.getReader();
      if (!reader) throw new Error('No response body');
      const decoder = new TextDecoder();
      let buffer = '';
      let content = '';

      while (true) {
        const { done, value } = await reader.read();
        if (done) break;
        buffer += decoder.decode(value, { stream: true });

        let newlineIdx: number;
        while ((newlineIdx = buffer.indexOf('\n')) !== -1) {
          let line = buffer.slice(0, newlineIdx);
          buffer = buffer.slice(newlineIdx + 1);
          if (line.endsWith('\r')) line = line.slice(0, -1);
          if (!line.startsWith('data: ')) continue;
          const jsonStr = line.slice(6).trim();
          if (jsonStr === '[DONE]') break;
          try {
            const parsed = JSON.parse(jsonStr);
            const delta = parsed.choices?.[0]?.delta?.content;
            if (delta) {
              content += delta;
              setItinerary(content);
            }
          } catch { /* partial */ }
        }
      }
    } catch (e: any) {
      if (e.name !== 'AbortError') {
        toast({ title: 'Error', description: 'Failed to generate itinerary', variant: 'destructive' });
      }
    } finally {
      setLoading(false);
    }
  };

  if (!user) {
    return (
      <div className="bg-primary/5 border border-primary/10 rounded-xl p-6 text-center">
        <Sparkles className="h-8 w-8 text-primary mx-auto mb-3" />
        <h3 className="font-display text-lg font-semibold mb-2">AI Travel Itinerary</h3>
        <p className="text-muted-foreground text-sm mb-4">Sign in to generate a personalized travel itinerary for this destination.</p>
        <Link to="/auth" className="inline-flex items-center gap-2 bg-gradient-primary text-primary-foreground px-6 py-2.5 rounded-full text-sm font-medium hover:opacity-90 transition-opacity">
          Sign In to Generate
        </Link>
      </div>
    );
  }

  return (
    <div className="bg-primary/5 border border-primary/10 rounded-xl p-6">
      <div className="flex items-center justify-between mb-4">
        <div className="flex items-center gap-2">
          <Sparkles className="h-5 w-5 text-primary" />
          <h3 className="font-display text-lg font-semibold">AI Travel Itinerary</h3>
        </div>
        <div className="flex items-center gap-2">
          {itinerary && !loading && (
            <Button
              onClick={() => downloadPdf(itinerary, gem.name)}
              size="sm"
              variant="outline"
            >
              <Download className="h-4 w-4 mr-1" /> Download PDF
            </Button>
          )}
          <Button
            onClick={generate}
            disabled={loading}
            size="sm"
            className="bg-gradient-primary text-primary-foreground"
          >
            {loading ? <><Loader2 className="h-4 w-4 mr-1 animate-spin" /> Generating...</> : 'Generate Itinerary'}
          </Button>
        </div>
      </div>

      {itinerary ? (
        <div className="prose prose-sm max-w-none dark:prose-invert">
          <div
            className="text-foreground/80 text-sm leading-relaxed"
            dangerouslySetInnerHTML={{ __html: DOMPurify.sanitize(simpleMarkdown(itinerary)) }}
          />
        </div>
      ) : (
        <p className="text-muted-foreground text-sm">
          Click "Generate Itinerary" to get an AI-powered travel plan for {gem.name}.
        </p>
      )}
    </div>
  );
};

export default ItineraryGenerator;
